name: "Kimball Deploy Actions"
description: "Deploy in a Kimball sort of way"
branding:
  icon: 'command'
  color: 'blue'
inputs:
  command:
    description: 'command to run'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
