name: "Kubernetes Action"
description: "Interacts with kubernetes clusters calling kubectl commands. Integrates support for AWS EKS."
branding:
  icon: 'anchor'
  color: 'blue'
inputs:
  commands:
    description: "Commands to run"
    required: true
outputs:
  result:
    description: "Output of the kubectl command run"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.commands }}
