name: Docker Action Test

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:

  build_docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Test
      uses: ./
      with:
        command: |
          aws-iam-authenticator help
          kustomize version
          kubectl version --client=true
          helm version
